version: '3.8'

networks:
  todo-net:

volumes:
  api-vol:
  
services:
  web-api:
    build: ./web
    command: python app.py
    ports:
      - target: 8080
        published: 5002
    expose:
      - "8080"
    networks:
      - todo-net
    volumes:
      - type: volume
        source: api-vol
        target: /app
      - type: bind
        source: ./app    # For Linux, use / backward slash to navigate to the current directory.
        
    
  
    
  